Update SSDB.js
fix bug: exception when callback is null.

            callback(['error']);
            ^
TypeError: undefined is not a function
    at Socket.<anonymous> (SSDB.js:32:13)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)